language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - 'pip install pipenv'
  - 'pipenv install'
# command to run tests
script:
  - 'python -m pytest --cov=app tests/'
  - 'flake8 app --statistics --count'
