version: '3.7'
services:

  resources:
    image: resources:latest
    build: .
    container_name: resources01
    environment:
    - SQLALCHEMY_DATABASE_URI=postgresql://user_name:change_password@127.0.0.1:5432/resources
    env_file:
    - .env
    volumes:
    - ./src:/src
    ports:
    - 8000:8000
    depends_on:
    - db

  db:
    image: postgres:10.1-alpine
    container_name: pg01
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: